name: Scrape LeetCode and Save Artifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape-leetcode:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure this matches your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create the necessary directories
      - name: Create directories
        run: mkdir -p files/description

      # Run the scraping script
      - name: Run description.js
        run: node description.js

      # Save the scraped data as an artifact
      - name: Upload scraped data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: files/description

      # (Optional) Post clean-up after saving artifacts
      - name: Clean up
        run: rm -rf files/description
