name: Scrape LeetCode Descriptions

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the scraping script
      - name: Run description scraper
        run: node description.js

      # Step 5: Upload the 'files/description' directory as an artifact
      - name: Upload scraped descriptions
        uses: actions/upload-artifact@v3
        with:
          name: leetcode-descriptions
          path: files/description/
